// packages/solid-uploader/src/index.tsx
import { onCleanup } from 'solid-js';
import { createStore, reconcile } from 'solid-js/store';
export * from '@verbpatch/headless-uploader';

import {
  useUploader as createUploader,
  UploaderConfig,
  UploaderState,
  UploaderInterface,
} from '@verbpatch/headless-uploader';

/**
 * Solid uploader instance that includes the reactive state
 */
export interface SolidUploader extends Omit<UploaderInterface, 'getState'> {
  state: UploaderState;
}

/**
 * Solid hook for using the uploader
 * @param config - Uploader configuration
 * @returns The uploader instance and its reactive state
 */
export function useUploader(config: UploaderConfig = {}): SolidUploader {
  const [state, setState] = createStore<UploaderState>({
    files: [],
    uploadingFiles: [],
    completedFiles: [],
    failedFiles: [],
    queuedFiles: [],
    totalProgress: { loaded: 0, total: 0, percentage: 0 },
    isUploading: false,
    isPaused: false,
  });

  function refresh() {
    if (!uploader) return;
    const rawState = uploader.getState();
    const newState: UploaderState = {
      ...rawState,
      files: rawState.files.map((f) => ({ ...f, progress: { ...f.progress } })),
      uploadingFiles: rawState.uploadingFiles.map((f) => ({ ...f, progress: { ...f.progress } })),
      completedFiles: rawState.completedFiles.map((f) => ({ ...f, progress: { ...f.progress } })),
      failedFiles: rawState.failedFiles.map((f) => ({ ...f, progress: { ...f.progress } })),
      queuedFiles: rawState.queuedFiles.map((f) => ({ ...f, progress: { ...f.progress } })),
      totalProgress: { ...rawState.totalProgress },
    };
    setState(reconcile(newState));
  }

  const uploader: UploaderInterface = createUploader({
    ...config,
    onFilesAdded: (files) => {
      refresh();
      config.onFilesAdded?.(files);
    },
    onQueueChange: (files) => {
      refresh();
      config.onQueueChange?.(files);
    },
    onStateChange: (file) => {
      refresh();
      config.onStateChange?.(file);
    },
    onFilesRejected: (errors) => {
      refresh();
      config.onFilesRejected?.(errors);
    },
    onValidationStart: (files) => {
      refresh();
      config.onValidationStart?.(files);
    },
    onValidationComplete: (results) => {
      refresh();
      config.onValidationComplete?.(results);
    },
    onBeforeUpload: async (file) => {
      const result = await config.onBeforeUpload?.(file);
      refresh();
      return result;
    },
    onUploadStart: (file) => {
      refresh();
      config.onUploadStart?.(file);
    },
    onUploadProgress: (file, progress) => {
      refresh();
      config.onUploadProgress?.(file, progress);
    },
    onChunkStart: (file, chunk) => {
      refresh();
      config.onChunkStart?.(file, chunk);
    },
    onChunkComplete: (file, chunk) => {
      refresh();
      config.onChunkComplete?.(file, chunk);
    },
    onUploadPause: (file) => {
      refresh();
      config.onUploadPause?.(file);
    },
    onUploadResume: (file) => {
      refresh();
      config.onUploadResume?.(file);
    },
    onUploadCancel: (file) => {
      refresh();
      config.onUploadCancel?.(file);
    },
    onUploadSuccess: (file, response) => {
      refresh();
      config.onUploadSuccess?.(file, response);
    },
    onUploadError: (file, error) => {
      refresh();
      config.onUploadError?.(file, error);
    },
    onRetry: (file, attempt) => {
      refresh();
      config.onRetry?.(file, attempt);
    },
    onAllComplete: (files) => {
      refresh();
      config.onAllComplete?.(files);
    },
    onMetadataExtracted: (file, metadata) => {
      refresh();
      config.onMetadataExtracted?.(file, metadata);
    },
    onPreviewGenerated: (file, preview) => {
      refresh();
      config.onPreviewGenerated?.(file, preview);
    },
  });

  refresh();

  onCleanup(() => {
    uploader.destroy();
  });

  return {
    ...uploader,
    state,
    removeFile: async (fileId: string) => {
      await uploader.removeFile(fileId);
      refresh();
    },
    clearAll: async () => {
      await uploader.clearAll();
      refresh();
    },
    updateConfig: (c) => {
      uploader.updateConfig(c);
      refresh();
    },
    handleDrop: async (event: DragEvent) => {
      await uploader.handleDrop(event);
      refresh();
    },
    handleFileSelect: async (event: Event) => {
      await uploader.handleFileSelect(event);
      refresh();
    },
  };
}

// packages/preact-uploader/src/index.tsx
import { useState, useEffect, useMemo, useRef } from 'preact/hooks';
export * from '@verbpatch/headless-uploader';

import { useUploader as createUploader, UploaderConfig } from '@verbpatch/headless-uploader';

/**
 * Preact hook for using the uploader
 * @param config - Uploader configuration
 * @returns The uploader instance and its current state
 */
export function useUploader(config: UploaderConfig = {}) {
  const configRef = useRef(config);
  configRef.current = config;

  const [, setStateChanged] = useState(0);

  const uploader = useMemo(() => {
    const updateState = () => {
      setStateChanged((prev) => prev + 1);
    };

    const instance = createUploader({
      ...config,
      onFilesAdded: (files) => {
        configRef.current.onFilesAdded?.(files);
        updateState();
      },
      onQueueChange: (files) => {
        configRef.current.onQueueChange?.(files);
        updateState();
      },
      onStateChange: (file) => {
        configRef.current.onStateChange?.(file);
        updateState();
      },
      onFilesRejected: (errors) => {
        configRef.current.onFilesRejected?.(errors);
        updateState();
      },
      onValidationStart: (files) => {
        configRef.current.onValidationStart?.(files);
        updateState();
      },
      onValidationComplete: (results) => {
        configRef.current.onValidationComplete?.(results);
        updateState();
      },
      onBeforeUpload: async (file) => {
        const result = await configRef.current.onBeforeUpload?.(file);
        updateState();
        return result;
      },
      onUploadStart: (file) => {
        configRef.current.onUploadStart?.(file);
        updateState();
      },
      onUploadProgress: (file, progress) => {
        configRef.current.onUploadProgress?.(file, progress);
        updateState();
      },
      onChunkStart: (file, chunk) => {
        configRef.current.onChunkStart?.(file, chunk);
        updateState();
      },
      onChunkComplete: (file, chunk) => {
        configRef.current.onChunkComplete?.(file, chunk);
        updateState();
      },
      onUploadPause: (file) => {
        configRef.current.onUploadPause?.(file);
        updateState();
      },
      onUploadResume: (file) => {
        configRef.current.onUploadResume?.(file);
        updateState();
      },
      onUploadCancel: (file) => {
        configRef.current.onUploadCancel?.(file);
        updateState();
      },
      onUploadSuccess: (file, response) => {
        configRef.current.onUploadSuccess?.(file, response);
        updateState();
      },
      onUploadError: (file, error) => {
        configRef.current.onUploadError?.(file, error);
        updateState();
      },
      onRetry: (file, attempt) => {
        configRef.current.onRetry?.(file, attempt);
        updateState();
      },
      onAllComplete: (files) => {
        configRef.current.onAllComplete?.(files);
        updateState();
      },
      onMetadataExtracted: (file, metadata) => {
        configRef.current.onMetadataExtracted?.(file, metadata);
        updateState();
      },
      onPreviewGenerated: (file, preview) => {
        configRef.current.onPreviewGenerated?.(file, preview);
        updateState();
      },
    });

    return {
      ...instance,
      removeFile: async (fileId: string) => {
        await instance.removeFile(fileId);
        updateState();
      },
      clearAll: async () => {
        await instance.clearAll();
        updateState();
      },
    };
  }, []);

  useEffect(() => {
    return () => {
      uploader.destroy();
    };
  }, [uploader]);

  return {
    ...uploader,
    state: uploader.getState(),
  };
}
